      SUBROUTINE MA27ID(ICNTL, CNTL)
          INTEGER ICNTL(30)
          DOUBLE PRECISION CNTL(5)
          RETURN
      END SUBROUTINE MA27ID

      SUBROUTINE MA27AD(N, NZ, IRN, ICN, IW, LIW, IKEEP, IW1, NSTEPS,
     &                  IFLAG, ICNTL, CNTL, INFO, OPS)
          INTEGER IFLAG, LIW, N, NSTEPS, NZ, ICNTL(30), INFO(20),
     &            ICN(*), IKEEP(N,3), IRN(*), IW(LIW), IW1(N,2)
          DOUBLE PRECISION CNTL(5), OPS
          RETURN
      END SUBROUTINE MA27AD

      SUBROUTINE MA27BD(N,NZ,IRN,ICN,A,LA,IW,LIW,IKEEP,NSTEPS,MAXFRT,
     &                  IW1,ICNTL,CNTL,INFO)
          INTEGER LA, LIW, MAXFRT, N, NSTEPS, NZ, ICN(*), IKEEP(N,3),
     &            IRN(*), IW(LIW), IW1(N), ICNTL(30), INFO(20)
          DOUBLE PRECISION A(LA), CNTL(5)
          RETURN
      END SUBROUTINE MA27BD

      SUBROUTINE MA27CD(N, A, LA, IW, LIW, W, MAXFRT, RHS, IW1, NSTEPS,
     &                  ICNTL, INFO)
          INTEGER LA, LIW, MAXFRT, N, NSTEPS, IW(LIW), IW1(NSTEPS),
     &            ICNTL(30), INFO(20)
          DOUBLE PRECISION A(LA), RHS(N), W(MAXFRT)
          RETURN
      END SUBROUTINE MA27CD
