      SUBROUTINE MA57ID(CNTL, ICNTL)
          DOUBLE PRECISION CNTL(5)
          INTEGER ICNTL(20)
          RETURN
      END SUBROUTINE MA57ID

      SUBROUTINE MA57AD(N, NE, IRN, JCN, LKEEP, KEEP, IWORK, ICNTL,
     &                  INFO, RINFO)
          INTEGER N, NE, IRN(NE), JCN(NE), IWORK(5*N), LKEEP,
     &            KEEP(LKEEP), ICNTL(20), INFO(40)
          DOUBLE PRECISION RINFO(20)
          RETURN
      END SUBROUTINE MA57AD

      SUBROUTINE MA57BD(N, NE, A, FACT, LFACT, IFACT, LIFACT,
     &                  LKEEP, KEEP, PPOS, ICNTL, CNTL, INFO, RINFO)
          INTEGER N, NE, LFACT, LIFACT, LKEEP
          DOUBLE PRECISION A(NE), FACT(LFACT), CNTL(5), RINFO(20)
          INTEGER IFACT(LIFACT), INFO(40), KEEP(LKEEP),
     &            PPOS(N), ICNTL(20)
          RETURN
      END SUBROUTINE MA57BD

      SUBROUTINE MA57CD(JOB, N, FACT, LFACT, IFACT, LIFACT, NRHS, RHS,
     &                  LRHS, W, LW, IW1, ICNTL, INFO)
          INTEGER JOB, N, LFACT, LIFACT, NRHS, LRHS, LW
          DOUBLE PRECISION FACT(LFACT), RHS(LRHS, NRHS), W(LW)
          INTEGER IFACT(LIFACT), IW1(N), ICNTL(20), INFO(40)
          RETURN
      END SUBROUTINE MA57CD

      SUBROUTINE MA57DD(JOB, N, NE, A, IRN, JCN, FACT, LFACT, IFACT,
     &                  LIFACT, RHS, X, RESID, W, IW, ICNTL, CNTL,
     &                  INFO, RINFO)
         INTEGER JOB, N, NE, LFACT, LIFACT, IRN(NE), JCN(NE),
     &           IFACT(LIFACT), IW(N), ICNTL(20), INFO(40)
         DOUBLE PRECISION A(NE), FACT(LFACT), RHS(N), X(N), RESID(N),
     &                    CNTL(5), RINFO(20), W(N, *)
         RETURN
      END SUBROUTINE MA57DD

      SUBROUTINE MA57ED(N, IC, KEEP, FACT, LFACT, NEWFAC, LNEW, IFACT,
     &                  LIFACT, NEWIFC, LINEW, INFO)
         INTEGER N, IC, KEEP(*), LFACT, LNEW, LIFACT, LINEW, INFO(40)
         DOUBLE PRECISION FACT(LFACT), NEWFAC(LNEW)
         INTEGER IFACT(LIFACT), NEWIFC(LINEW)
         RETURN
      END SUBROUTINE MA57ED
